FROM java:8-alpine
MAINTAINER Your Name <you@example.com>

ADD target/uberjar/highcharts-reagent-gp.jar /highcharts-reagent-gp/app.jar

EXPOSE 3000

CMD ["java", "-jar", "/highcharts-reagent-gp/app.jar"]
